version: "3" # composeファイルのバージョン
services:
    app: # サービス名
        build: . # ビルドに使うDockerfileの場所
        tty: true # コンテナの永続化
        ports: # ホストOSのポートとコンテナのポートをつなげる
            - "8081:8081"
        volumes:
            - ./app:/go/src/app # マウントディレクトリ
